Script started on Fri 06 Nov 2015 04:00:30 PM PST
[tmoor008@hammer src]$ g++ -Wall -Werror -ansi -pedantic rshell.cc
[tmoor008@hammer src]$ ./a.out
tmoor008@hammer.cs.ucr.edu$ echo start # this is a comment
start
tmoor008@hammer.cs.ucr.edu$ echo go && echo stop # comment after multiple commands
go
stop
tmoor008@hammer.cs.ucr.edu$ echo go && cal; echo meow || mkdir yes # comments
go
    November 2015
Su Mo Tu We Th Fr Sa
 1  2  3  4  5	6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30

meow
tmoor008@hammer.cs.ucr.edu$ ls -a; #no dir yes
.  ..  a.out  commented_command.script	rshell.cc
tmoor008@hammer.cs.ucr.edu$ ls -a;#comment no spaces
.  ..  a.out  commented_command.script	rshell.cc
tmoor008@hammer.cs.ucr.edu$ mkdir hello # makes a directory
tmoor008@hammer.cs.ucr.edu$ ls -a; # did it work
.  ..  a.out  commented_command.script	hello  rshell.cc
tmoor008@hammer.cs.ucr.edu$ rm hello # remove the directory
rm: cannot remove `hello': Is a directory
tmoor008@hammer.cs.ucr.edu$ rm -r hello # remove the directory
tmoor008@hammer.cs.ucr.edu$ ls -a # should work ls -a
.  ..  a.out  commented_command.script	rshell.cc
tmoor008@hammer.cs.ucr.edu$ cal#no spaces
    November 2015
Su Mo Tu We Th Fr Sa
 1  2  3  4  5	6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30

tmoor008@hammer.cs.ucr.edu$ date# space before
Fri Nov	 6 16:03:37 PST 2015
tmoor008@hammer.cs.ucr.edu$ date #space after
Fri Nov	 6 16:03:42 PST 2015
tmoor008@hammer.cs.ucr.edu$ #all a comment
tmoor008@hammer.cs.ucr.edu$ echo monday #echo tuesday
monday
tmoor008@hammer.cs.ucr.edu$ echo dragon # ls -a; mkdir rider # more comments # all should be a comment
dragon
tmoor008@hammer.cs.ucr.edu$ echo dragon#comment
dragon
tmoor008@hammer.cs.ucr.edu$ echo giraffe #
giraffe
tmoor008@hammer.cs.ucr.edu$ echo meow#
meow
tmoor008@hammer.cs.ucr.edu$ #
tmoor008@hammer.cs.ucr.edu$ echo fast # echo gotta go
fast
tmoor008@hammer.cs.ucr.edu$ echo #

tmoor008@hammer.cs.ucr.edu$ echo#

tmoor008@hammer.cs.ucr.edu$ echo end # good tests with comments
end
tmoor008@hammer.cs.ucr.edu$ exit
[tmoor008@hammer src]$ exit
exit

Script done on Fri 06 Nov 2015 04:07:26 PM PST
